Removing endpoint test and updating pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -1,15 +1,11 @@
-#!/bin/sh
+#!/bin/bash
 
-echo "*****Running unit tests******"
+echo "Running git pre-commit hook"
 
-git stash -q --keep-index
+./gradlew clean build
 
-./gradlew test
+RESULT=$?
 
-status=$?
-
-git stash pop -q
-
-echo "*****Done with unit tests******"
-
-exit $status
+# return 1 exit code if running checks fails
+[ $RESULT -ne 0 ] && exit 1
+exit 0
